### ISSUE TITLE
How to TOC ?

### ISSUE THREAD

**Issue by dlewin-vossloh** [thomas-chauvet/latex2pdf-action#2]
I've been using article template successfully on overleaf which generated a suitable TOC. 
But when using latex2pdf-action the TOC disappeared. Because there is no arguments like "--toc" in pandoc,  I guess that it's because a 2nd pass is needed. 
If yes how to do this with actions ?

**Comment by thomas-chauvet** [comment]
Hello,

I added a parameter called `toc` (check the `README`). It allows to compile the document twice to generate a ToC. Use version `1.1.0`.

Let me know if it works for you.

For now, I'll close the issue. There is an example on how to generate ToC in the github action in the repo.

Cheers!
